# **Useful Array Constructors**

## Zeros Array

In [1]:
import numpy as np

# Creating zero array
z_arr = np.zeros((3,3))

print(z_arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Ones Array

In [2]:
# Creating Ones array
o_arr = np.ones((3,3))

print(o_arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Full Array

Arrays initialized with custom filled elements.

In [4]:
# Creating '2' full array
t_arr = np.full((3,3), 2)

print(t_arr)


[[2 2 2]
 [2 2 2]
 [2 2 2]]


## Identity Matrix Array

Used to create identity matrices with given dimension.

Both np.eye and np.identity create identity matrices, but:

-   np.eye(N, M): creates an NxM matrix, with 1s on the main diagonal. More flexible.

-   np.identity(N): creates a square NxN identity matrix only.

In [16]:
# creating with eye()
e_arr = np.eye(2,3)

# creating with identity()
i_arr = np.identity(3)

print(e_arr, "\n")

print(i_arr)

[[1. 0. 0.]
 [0. 1. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Linespace Array

-   Creates evenly spaced values between start and stop.

-   You specify how many points (num).

In [21]:
# Craeting an array of num from 02 with 5 elements
arr1 = np.linspace(0, 2, 5)

print(arr1)


[0.  0.5 1.  1.5 2. ]


## ARange Array

-   Like Python’s range(), but returns an array.

-   You specify step size, not number of points.

In [23]:
# Creating an array with range(0,10,2)
arr2 = np.arange(0, 10, 2)

print(arr2)


[0 2 4 6 8]


## Meshgrid Array

-   Creates coordinate grids from x and y arrays (often from linspace or arange).

-   Useful in 2D/3D plotting or function evaluation over a grid.

In [ ]:
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 2)
X, Y = np.meshgrid(x, y)
# X, Y are 2D arrays for grid coordinates
print(x)
print(y, '\n\n')

print(X)
print(Y)


[0.  0.5 1. ]
[0. 1.] 


[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]
