# **Arrays**

- NumPy is used to work with arrays. The array object in NumPy is called **"ndarray"**
#### Ex:

In [40]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))


[1 2 3]
<class 'numpy.ndarray'>


-   To create an ndarray we can pass a *list, tuple or any array like object* into the **array()**
 method, and it will be converted into an ndarray.

#### Ex: Creating an ndarray using a *tuple*:

In [ ]:

arr_tup = np.array((1,2,3,4,5))
print(arr_tup)


array([1, 2, 3, 4, 5])

## Dimensions in Arrays

A Dimension in arrays is one level of array depth (nested arrays).

**Nested Arrays:** are the arrays that have arrays as their elements.

### 0-D Arrays

O-D arrays, or Scalars, are the elements of an array. Each value of an array is a 0-D array.

#### Ex:

In [42]:
# Creating a 0-D array

zr_arr = np.array(46)
print(zr_arr)


46


### 1-D Arrays

An array containg only values.

#### Ex:

In [ ]:
nums = np.array((1,2,3))
print(nums)

array([1, 2, 3])

### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent ***matrix*** or ***2nd order tensors***.

#### Ex:

In [44]:
# Creating by give a nested list as input

arr_2d = np.array([[1,2],[3,4]])
print(arr_2d)


[[1 2]
 [3 4]]


### 3-D Arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

#### Ex:

In [45]:
# Double nested lists

arr_3d = np.array([[[1,2],[4,5]],[[7,7],[8,8]]])
print(arr_3d)


[[[1 2]
  [4 5]]

 [[7 7]
  [8 8]]]


## Check No of Dimensions

NumPy Arrays procides the ***ndim*** attribute that returns an integer that tells us how many dimensions the array have.

#### Ex:

In [46]:
# No of dimensions of: arr, arr_2d, and arr_3d.
print(arr.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)


1
2
3


## Higher Dimension Arrays

Arrays can be of any number of Dimension.

When an array is created, you can define the number of dimension by using the ***ndim*** argument.

We mostly only use arrays till Dimension 4, which is used in ML, and even higher level arryas are 
only used for specific problems (scientific calculations, maths, etc).

##### Ex: Creating a 5-D array

In [50]:
arr_5d = np.array([1,2,3,4,5], ndmin=5 )
print(arr_5d)

[[[[[1 2 3 4 5]]]]]
