# **NumPy Array Slicing**

## Slicing Arrays

Slicing in python means taking elements from one given index to another given index.  
-   We pass slice instead of index like this: **[start:end]**. 

-   We can also define the step, like this: **[start:end:step]**.  

-   If we don't pass start its considered 0  

-   If we don't pass end its considered length of array in that dimension  

-   If we don't pass step its considered 1

#### Ex:

In [6]:
import numpy as np

# creating an array
arr = np.array([1,2,3,4,5])

# Slicing from 1-3
print(arr[0:3])

# Slicing from 3-5
print(arr[2:5])


[1 2 3]
[3 4 5]


#### Ex: Reverse Slicing 

In [9]:
# slicing from 3-5
print(arr[-3:])

[3 4 5]


## Step

The **step** in indexing decides the no of element to skip while iterating the array.

#### Ex:

In [15]:
# printing every 2nd element in the arr of (1-10)
nums = np.array(range(1,11))
print(nums[1::2])


[ 2  4  6  8 10]


## Slicing 2-D Array

It is done in the same manner as normal slicing, but we first navigate through the array by indexing.

#### Ex:

In [ ]:
# creating a 2-D array
arr_2d = np.array([[1,2,3],[4,5,6]])

# Slicing the 2nd array from 5-6
print(arr_2d[1,1:3])


[5 6]
