# **NumPy Array Shape**

## Shape of an Array

***Shape of an array is no of elements in each Dimension.***

## Get the Shape of an Array

NumPy arrays have an attribute called **shape** that returns a tuple with each index having the number of corresponding elements.

#### Shape = ( 1-D, 2-D, 3-D, ..., n-D )
-   1-D: elements in the 1st dimension
-   2-D: elements in the 2nd dimension

#### Ex: Printing the shape of a 5-D array.

In [12]:
import numpy as np

# craeting a 5d array
arr_5d = np.array([1],ndmin=5)
print(arr_5d)

# printing shape
print('Shape:',arr_5d.shape)


[[[[[1]]]]]
Shape: (1, 1, 1, 1, 1)


# **NumPy Array Reshaping**



## Reshaping Arrays

The shape of array is the number of emlements in each Dimension.  

By reshaping an array we can change the no of elements within each dimension of an array.

To reshape an array object in NumPy we have a *reshape()* method. It takes numeric positional arguments  
where each number represent a dimension.

## 🔄 Basic Syntax
```python
reshaped = array.reshape(new_shape)

`Note`: To reshape an array, the no of elements in the original must be compatible with the disiered shape.

## 🧠 Core Principles

- **Element Count Must Match**  
  You can only reshape if the total number of elements stays the same.  
  Example:
  ```python
  np.array([1, 2, 3, 4]).reshape(2, 2)   # ✅ OK
  np.array([1, 2, 3, 4]).reshape(3, 2)   # ❌ Error
- **Use -1 to Auto-Infer a Dimension**  
  NumPy will calculate the correct size automatically.

- **Returns a View if Possible**  
  Reshape returns a view (shares memory) if layout allows. Otherwise, it returns a copy.

- **Row-Major Order (C-style) by Default**  
  Fills data row by row unless order='F' is specified.

## Converting 1-D to 2-D

In [48]:
# creating 1d array
one_dim = np.array([1,2,3,4])

# reshaping
two_dim = one_dim.reshape(2,2)

print(one_dim)
print(two_dim)

[1 2 3 4]
[[1 2]
 [3 4]]


## Converting 2-D to 3-D

In [ ]:
# reshaping
three_dim = two_dim.reshape(1,1,-1)

print(three_dim)


[1 2 4 4]
[[[1 2 4 4]]]


## Return Copy or View

In [ ]:
# checking the base of returning arrays
print(two_dim.base)
print(two_dim.base)


[1 2 4 4]
[1 2 4 4]


## Unknown Dimension

The *reshape()* can have one "unkown" Dimension.  

Meaning that we don't have to calculate the no of elements in that Dimension, NumPy will calculate it.

**Pass** `-1` as the value, and NumPy will calculate the number of elements in that Dimension.

#### Ex:

In [ ]:
# creating an 1-D array
nums = np.array([1,2,3,4,5,6,7,8])

# reshaping with -1
nums_3d = nums.reshape(2,2,-1)  # becomes (2,2,2)

print(nums_3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening the arrays

Flattening means converting multi-dimensional arrays into 1-D array.  

We can use **reshape(-1)** to do this. '-1' automatically converts to no of elements.

#### Ex:

In [88]:
# flattening 3-d array
nums_3d_flate = nums_3d.reshape(-1)

print(nums_3d_flate)


[1 2 3 4 5 6 7 8]
