# **NumPy Joining Array**

## Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.  

We pass a sequence of arrays that we want to join to the **concatenate()** function,  
along with the *axis*. If *axis* is not explicitly passed, it is taken as `0`.

#### Ex:

In [5]:
import numpy as np

# creating 2 arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# joining both arrays
arr3 = np.concatenate((arr1,arr2))

print(arr3)


[1 2 3 4 5 6]


### Axis in Arrays

**Axis refers to the dimension along which the action in being performed.**  

- A 1-D array have zero axis, only one dimension to go through.

- In 2-D arrays, there are 2 axis being `0` and `2`.

    Axis 0 ↓ (rows)     
    [[1, 2, 3],  ← row 0
    [4, 5, 6]]  ← row 1 
        →               
    Axis 1 (columns)    

#### Ex: Column wise sum.

In [ ]:
# creating a 2d array
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# sum
print(np.sum(a, axis=0))


[5 7 9]


#### Ex: Row wise sum.

In [18]:
# a = ([[1, 2, 3],
#      [4, 5, 6])

# sum
print(np.sum(a, axis=1))


[ 6 15]


## Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.  

We can concatenate two 1-D arrays along the second axis which would result in putting them  
one over the other, ie. stacking.  

We pass a sequence of arrays that we want to join to the **stack()** method along with the  
axis. If axis is not explicitly passed it is taken as 0.

#### Ex:

In [25]:
# creating 2 arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# stacking both arrays
arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


### Stacking along Rows

NumPy provides a helper function: **hstack()** to stack along rows.

#### Ex:

In [26]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking along Columns

NumPy provides a helper function: **vstack()**  to stack along columns.

#### Ex:

In [27]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking along Height (depth)

NumPy provides a helper function: **dstack()** to stack along height, which is the same as depth.

#### Ex:

In [28]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
