# **NumPy Simple Airthmetics** 

We could use airthmetic operators `+` `-` `*` `/` directly between NumPy arrays, but this  
section discusses an extension of the same where we have function that can take array like  
objects e.g. lists, tuples, etc. And perform airthmectic operations *conditionally*.
> **Airthmetic Conditionally**: means that we can define condition where the arithmetic operation should happen.  

All of the discussed arithmetic functions take a **"where"** parameter in which we can specify that condition.



In [19]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])

# using where
result = np.zeros_like(a)
np.add(a, b, where=(a > 1), out = result)

print(result)


[0 6]


## Addition

The `add()` function sums the content of two arrays, and return the results in a new array.  

#### Ex:

In [20]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)


[30 32 34 36 38 40]


## Subtraction

The `subtract()` function subtracts the values from one array with the values from another array,  
and return the results in a new array.

#### Ex:

In [21]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)


[-10  -1   8  17  26  35]


## Multiplication  

The `multiply()` function multiplies the values from one array with the values from another array,  
and return the results in a new array.

#### Ex:

In [22]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)


[ 200  420  660  920 1200 1500]


## Division  

The `divide()` function divides the values from one array with the values from another array,  
and return the results in a new array.

#### Ex: 

In [23]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)


[ 3.33333333  4.          3.          5.         25.          1.81818182]


## Power  

The `power()` function rises the values from the first array to the power of the values of the second array,  
and return the results in a new array.

#### Ex:

In [24]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([2, 3, 5, 6, 7, 8])

newarr = np.power(arr1, arr2)

print(newarr)


[      1       8     243    4096   78125 1679616]


## Remainder  

Both the `mod()` and the `remainder()` functions return the remainder of the values in the first  
array corresponding to the values in the second array, and return the results in a new array.

#### Ex: *mod()*

In [25]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)


[ 1  6  3  0  0 27]


#### Ex: *remainder()*

In [26]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)


[ 1  6  3  0  0 27]


## Quotient and Mod

The `divmod()` function return both the quotient and the mod. The return value is two arrays,  
the first array contains the quotient and second array contains the mod.

#### Ex: 

In [27]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)


(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


## Absolute Values

Both the `absolute()` and the `abs()` functions do the same absolute operation element-wise  
but we should use `absolute()` to avoid confusion with python's inbuilt `math.abs()`.

#### Ex: 

In [29]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)


[1 2 1 2 3 4]
